import "./globals.css";
import { Inter } from "next/font/google";

import "bootstrap/dist/css/bootstrap.min.css";
import { AuthContextProvider } from "./context/authContext";
import { SocketContextProvider } from "./context/SocketContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Meet",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <SocketContextProvider>{children}</SocketContextProvider>
        </AuthContextProvider>
      </body>
    </html>
  );
}
